### ISSUE TITLE
Open quotes in comments triggers a parsing error

### ISSUE THREAD

**Issue by YaZko** [rocq-prover/vsrocq#737]
It seems like an orphan quote insight of a comment is incorrectly handled at the moment.
I.e. I expect the following to trigger no error nor warning, but it displays all of the file after the quote as a parsing error.

On `2.1.0+coq8.19`.

``` coq
Definition x := 9.

(* " *)

Lemma foo : x = 9.
reflexivity.
Qed.
```

Best,
Yannick

**Comment by rtetley** [comment]
Ah cool ! I was about to test it out on other IDEs and see what happens there, but I believe that handling this would require parsing comments, and is related to: #728
Thanks for reporting !
